-- 建立数据库
CREATE DATABASE `PunchRing` DEFAULT charset=utf8;
USE `PunchRing`;

-- 用户表
DROP TABLE IF EXISTS `wx_user`;
CREATE TABLE IF NOT EXISTS `wx_user`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `wx_openid` VARCHAR(64) NOT NULL COMMENT '微信用户唯一标识 OpenID',
  `wx_session_key` VARCHAR(32) NOT NULL COMMENT '微信会话密钥 session_key',
  `wx_info` TEXT NOT NULL COMMENT '微信用户信息 json',
  `reg_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updata_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态(单选):0=封锁,1=激活',
  PRIMARY KEY(`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `wx_openid` (`wx_openid`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';

-- 打卡表
DROP TABLE IF EXISTS `punch_card`;
CREATE TABLE IF NOT EXISTS `punch_card`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `uid` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `main` VARCHAR(512) NOT NULL COMMENT '打卡内容',
  `place` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '打卡地点',
  `images` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '打卡图片(可多个) json',
  `video` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '打卡视频',
  `time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `private` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '私密(单选):0=否,1=是',
  `status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态(单选):0=删除,1=显示',
  PRIMARY KEY(`id`),
  KEY `uid` (`uid`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='打卡表';

-- 点赞表
DROP TABLE IF EXISTS `star`;
CREATE TABLE IF NOT EXISTS `star`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `uid` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `cid` INT UNSIGNED NOT NULL COMMENT '打卡ID',
  `time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态(单选):0=未激活,1=激活',
  PRIMARY KEY(`id`),
  KEY `uid` (`uid`),
  KEY `cid` (`cid`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='点赞表';